import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <nav>
        <a href="/roles">Roles</a>
        <a href="/users">Users</a>
      </nav>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}


    31	        <nav>
    32	          <a href="/roles">Roles</a>
    33	          <a href="/users">Users</a>
    34	        </nav>


        <nav>
          <a href="/roles">Roles</a>
          <a href="/users">Users</a>
        </nav>
      </body>
    </html>
  );
}
